source 'https://api.berkshelf.com'

cookbook 'c6mongo', git: 'git@bitbucket.org:cinema6/c6mongo.git'
cookbook 'c6env', git: 'git@bitbucket.org:cinema6/c6env.git'
cookbook 'maint', git: 'git@bitbucket.org:cinema6/maint.git'
cookbook 'auth', git: 'git@bitbucket.org:cinema6/auth.git'
cookbook 'ads', git: 'git@bitbucket.org:cinema6/ads.git'
cookbook 'collateral', git: 'git@bitbucket.org:cinema6/collateral.git'
cookbook 'content', git: 'git@bitbucket.org:cinema6/content.git'
cookbook 'monitor', git: 'git@bitbucket.org:cinema6/monitor.git'
cookbook 'orgSvc', git: 'git@bitbucket.org:cinema6/orgSvc.git'
cookbook 'search', git: 'git@bitbucket.org:cinema6/search.git'
cookbook 'userSvc', git: 'git@bitbucket.org:cinema6/userSvc.git'
cookbook 'vote', git: 'git@bitbucket.org:cinema6/vote.git'
