(function(){'use strict';}());
module.exports.id3Info   = require('./id3');
module.exports.ffmpeg    = require('./ffmpeg');
module.exports.assemble  = require('./assemble');
module.exports.vocalWare = require('./vocalware');
module.exports.logger    = require('./logger');
module.exports.s3util    = require('./s3util');
module.exports.uuid      = require('./uuid');
module.exports.config    = require('./config');
module.exports.daemon    = require('./daemon');
